[package]
name = "qu-robot"
version = "0.1.0"
build = "build.rs"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-macro = "2.1.8"
gtk = { version = "0.7.3", package = "gtk4", features = ["v4_12"] }
ndarray = "0.15.6"
plotters = "0.3.5"
rand = "0.8.5"
rsrl = "0.8.1"
spaces = "6.0.0"

[build-dependencies]
glib-build-tools = "0.18.0"
