[package]
name = "qu-robot"
version = "0.1.0"
build = "build.rs"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4", features = ["compress-brotli", "macros"], default-features = false }
gtk = { version = "0.7.3", package = "gtk4", features = ["v4_12"], optional = true, defaul_features = false }
ndarray = "0.15.6"
plotters = "0.3.5"
rand = "0.8.5"
rsrl = "0.8.1"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"

[build-dependencies]
glib-build-tools = "0.18.0"

[features]
native_ui = ["gtk"]
